version: '3.8'
services:
  idp-db:
    container_name: idp-db
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "idp-db"
      MYSQL_USER: "idp-user"
      MYSQL_PASSWORD: "password"
    ports:
      - "8085:3306"
    networks:
      - idp-subnet

  saml-idp:
    container_name: saml-idp
    build: ./saml-idp
    ports:
      - "8080:80"
    depends_on:
      - idp-db
    networks:
      - idp-subnet
      - global-net

  saml-idp-interface:
    container_name: saml-idp-interface
    build: ./saml-idp-interface
    ports:
      - "7070:80"
    depends_on:
      - idp-db
    networks:
      - idp-subnet
      - global-net

  sp-db:
    container_name: sp-db
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "sp-db"
      MYSQL_USER: "sp-user"
      MYSQL_PASSWORD: "password"
    ports:
      - "9095:3306"
    networks:
      - sp-subnet

  saml-sp:
    container_name: saml-sp
    build: ./saml-sp-node
    ports:
      - "9090:3000"
    depends_on:
      - sp-db
    networks:
      - sp-subnet
      - global-net

networks:
  idp-subnet:
  sp-subnet:
  global-net:
